### ISSUE TITLE
Add `ToImmutableArrayAsync` in addition to `ToArrayAsync`

### ISSUE THREAD

**Issue by xperiandri** [Gremlinq/ExRam.Gremlinq#1381]
**Is your feature request related to a problem? Please describe.**
We need to have `ImmutableArray` as output but preferably without an unnecessary allocation of an array.

**Describe the solution you'd like**
Add `ToImmutableArrayAsync` methods in addition to `ToArrayAsync`

**Describe alternatives you've considered**
Convert array to `ImmutableArray` with unnecessary allocation

**Consider sponsoring me**
I can contribute the feature if you approve

**Comment by danielcweber** [comment]
There is always `ToAsyncEnumerable` on any query, which you can do anything with (`ToImmutableArray` should be available in either System.Linq.Async or System.Interactive.Async). It's an easy extension method, I'm not sure it should go into the main library.

**Comment by xperiandri** [comment]
Sounds great, thanks!

**Comment by danielcweber** [comment]
Closing. The feature can easily be added by an extension method.
